### PR TITLE
Add react final-form

### PR DESCRIPTION
**Pull request by ivarnakken**

### CODE REVIEW

**Comment by ivarnakken** [comment]
> What was the plan here again? Can we merge this (since it's into dev)? :sunglasses:

hmm I don't quite remember. I cleaned up your shit, so I guess I reckoned you'd continue? 🤔 Merge it :shipit:

**Comment by ivarnakken** [comment]
image

**Comment by LudvigHz** [comment]
@ivarnakken Can I close this?

**Comment by norbye** [comment]
I'm leaving the unmodified changes here in case you guys want it for nostalgic reasons - but I've rebased the functionality to #867

**Comment by SmithPeder** [comment]
> nostalgic reasons

The amount of nostalgia I have for this change is close to zero

**Pull request closed without merging**
