### PR TITLE
Syncronize dev-branch

### PR DESCRIPTION
**Pull request by norbye**
As far as I can see this stuff has never been through a PR so I figured it was time to get it out there.

Just finished up the rebasing, so I haven't looked through this PR very thoroughly, although everything seems to run fine in the dev environment.

Added a last commit to fixup some of the things I got wrong - as it didn't seem worth it to stop at every one of the 290 commits it was behind to ensure it ran perfectly.

### CODE REVIEW

**Comment by SmithPeder** [comment]
And this works ey? If I remember correctly I did a bunch of random stuff in dev once 🤔 And not everything worked 🤔

**Comment by norbye** [comment]
> And this works ey? If I remember correctly I did a bunch of random stuff in dev once 🤔 And not everything worked 🤔 

Should probably test some more - but I have sent myself a couple of mails through it and so far it seems to work as expected.

**Review by ivarnakken — APPROVED** [review]
Haha you’re an MVP!! NextUI let’s go (at least until we replace it with Lego-bricks next week😁😁)

**Comment by norbye** [comment]
> at least until we replace it with Lego-bricks next week😁😁

Ah fuck ._.

**Pull request merged**
